module.exports = {
    CONNECTED : "CONNECTED",
    COMMUNITY_CHAT:"COMMUNITY_CHAT",
    TYPING:"TYPING",
    NOTIFICATION_SENT:'NOTIFICATIONS_SENT',
    NOTIFICATION_RECEIVED:'NOTIFICATION_RECEIVED',
    MESSAGE_RECEIVED:"MESSAGE_RECEIVED",
    MESSAGE_SENT:"MESSAGE_SENT",
}
